---
- name: Create disk partitions and file systems
  hosts: training
  become: yes

  vars:
    oracle_owner: oracle
    oracle_group: oinstall
    oracle_base: /u01/app/oracle
    oracle_mount: /u01/app/oracle/product
    oracle_client_19c: /u01/app/oracle/product/19c/client_1
    oracle_home_19c_zip: /software/Database/Oracle/19c/LINUX.X64_193000_client_home.zip
    oracle_home_19c_rsp: /software/Database/Oracle/19c

  tasks:

    - name: create oracle client 19c home directory and change ownership
      file:
        state: directory
        path: "{{ oracle_client_19c }}"
        owner: "{{ oracle_owner }}"
        group: "{{ oracle_group }}"
        recurse: yes

    - name: unzip oracle 19c client software
      unarchive:
        src: "{{ oracle_home_19c_zip }}"
        dest: "{{ oracle_client_19c }}"
        remote_src : yes
        owner: "{{ oracle_owner }}"
        group: "{{ oracle_group }}"

    - name: Run Installer for 19c client
      become_user: oracle
      #shell: "{{ oracle_client_19c }}/runInstaller -silent -responseFile {{ oracle_home_19c_rsp }}/client19c.rsp"
      action: shell "{{ oracle_client_19c }}/runInstaller -silent -responseFile {{ oracle_home_19c_rsp }}/client19c.rsp"

    - name: Run root.sh for 19c client
      action: shell "{{ oracle_client_19c }}/root.sh"
